// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface CreateUserRequest {
  name: string;
  email: string;
}

export interface UserResponse {
  id: number;
  name: string;
  email: string;
  createdAt: string;
}

export interface GetUserbyIdRequest {
  id: number;
}

export const USER_PACKAGE_NAME = "user";

/** UserService defines the gRPC service for managing user-related operations. */

export interface UserServiceClient {
  /**
   * CreateUser creates a new user with the provided details.
   * Returns the created user's details, including their unique identifier.
   * If the input data is invalid, returns an INVALID_ARGUMENT error.
   */

  createUser(request: CreateUserRequest): Observable<UserResponse>;

  /**
   * GetUserById retrieves a single user by their unique identifier.
   * Returns the user details if found, or a NOT_FOUND error if the user does not exist.
   */

  getUserbyId(request: GetUserbyIdRequest): Observable<UserResponse>;
}

/** UserService defines the gRPC service for managing user-related operations. */

export interface UserServiceController {
  /**
   * CreateUser creates a new user with the provided details.
   * Returns the created user's details, including their unique identifier.
   * If the input data is invalid, returns an INVALID_ARGUMENT error.
   */

  createUser(request: CreateUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  /**
   * GetUserById retrieves a single user by their unique identifier.
   * Returns the user details if found, or a NOT_FOUND error if the user does not exist.
   */

  getUserbyId(request: GetUserbyIdRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUser", "getUserbyId"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
