// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: wallet.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "wallet";

export interface CreateWalletRequest {
  userId: number;
}

export interface WalletResponse {
  id: number;
  userId: number;
  balance: number;
  createdAt: string;
}

export interface GetWalletByIdRequest {
  id: number;
}

export interface CreditWalletRequest {
  id: number;
  amount: number;
}

export interface DebitWalletRequest {
  id: number;
  amount: number;
}

export const WALLET_PACKAGE_NAME = "wallet";

/** WalletService defines the gRPC service for managing wallet-related operations. */

export interface WalletServiceClient {
  /**
   * CreateWallet creates a new wallet for a user with the provided details.
   * Returns the created wallet's details, including its unique identifier.
   * If the input data is invalid, returns an INVALID_ARGUMENT error.
   * Ensures a user exists before creating a wallet, returning a NOT_FOUND error if the user does not exist.
   */

  createWallet(request: CreateWalletRequest): Observable<WalletResponse>;

  /**
   * GetWalletById retrieves a single wallet by its unique identifier.
   * Returns the wallet details if found, or a NOT_FOUND error if the wallet does not exist.
   */

  getWalletById(request: GetWalletByIdRequest): Observable<WalletResponse>;

  /**
   * CreditWallet adds a specified amount to the wallet's balance.
   * Returns the updated wallet details after the credit operation.
   */

  creditWallet(request: CreditWalletRequest): Observable<WalletResponse>;

  /**
   * DebitWallet subtracts a specified amount from the wallet's balance.
   * Returns the updated wallet details after the debit operation.
   * If the wallet has insufficient funds for the debit operation, returns a FAILED_PRECONDITION
   */

  debitWallet(request: DebitWalletRequest): Observable<WalletResponse>;
}

/** WalletService defines the gRPC service for managing wallet-related operations. */

export interface WalletServiceController {
  /**
   * CreateWallet creates a new wallet for a user with the provided details.
   * Returns the created wallet's details, including its unique identifier.
   * If the input data is invalid, returns an INVALID_ARGUMENT error.
   * Ensures a user exists before creating a wallet, returning a NOT_FOUND error if the user does not exist.
   */

  createWallet(request: CreateWalletRequest): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  /**
   * GetWalletById retrieves a single wallet by its unique identifier.
   * Returns the wallet details if found, or a NOT_FOUND error if the wallet does not exist.
   */

  getWalletById(request: GetWalletByIdRequest): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  /**
   * CreditWallet adds a specified amount to the wallet's balance.
   * Returns the updated wallet details after the credit operation.
   */

  creditWallet(request: CreditWalletRequest): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  /**
   * DebitWallet subtracts a specified amount from the wallet's balance.
   * Returns the updated wallet details after the debit operation.
   * If the wallet has insufficient funds for the debit operation, returns a FAILED_PRECONDITION
   */

  debitWallet(request: DebitWalletRequest): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;
}

export function WalletServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createWallet", "getWalletById", "creditWallet", "debitWallet"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("WalletService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("WalletService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const WALLET_SERVICE_NAME = "WalletService";
